apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-logs-storage-0
  namespace: victoria-logs
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/zfs/docker-persistent/victoria-logs/vmlogs-0
    server: dnshost.domain.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-logs-storage-1
  namespace: victoria-logs
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/zfs/docker-persistent/victoria-logs/vmlogs-1
    server: dnshost.domain.com